### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by mady143** [aahmad4/Resume-Scanner#1]
Hi @aahmad4 ,
I clone your code and executed i successfully run your code but i had doubt on what bases your getting the percentage comparing with the job description and requirement 

actually its based on keywords or else anything else is their for the process can you explain it clearly ...
Thanks and Regards,
Manikantha Sekhar....

**Comment by aahmad4** [comment]
Hi @mady143 ,
I appreciate your interest in my program. The metric being used is cosine similarity.  This is a metric used to determine how similar two documents are, irrespective of their size. In standard mathematics, this metric will measure the cosine of the angle between two vectors projected in a multi-dimensional space. In this scenario, the two "vectors" are actually two arrays containing the word counts of the two documents. Cosine similarity works well for this type of program because even though there is a disparity in size between the job description and the proposed resume, cosine similarity can still orientate them to be close together. As far as comparing these two documents go and giving a similarity score, the two documents are compared in numerous amount of fields such as text analysis, keyword count and usage in context, the subject being conveyed in the text, and several other factors. You can learn more about it here https://www.sciencedirect.com/topics/computer-science/cosine-similarity
https://www.machinelearningplus.com/nlp/cosine-similarity/

Sincerely,
Ali Ahmad
